using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class weaponTest : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
    }

    // Update is called once per frame
    void Update()
    {
    }

    private void OnCollisionEnter2D(Collision2D other)
    {
        if (!other.gameObject.CompareTag("Player") && !other.gameObject.CompareTag("Enemy"))
        {
            
        }
            // Debug.Log("collision " + other.gameObject.name);
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (!other.gameObject.CompareTag("Player") && !other.gameObject.CompareTag("Enemy"))
        {
            
        }
            // Debug.Log("trigger " + other.gameObject.name);
    }
}